### ISSUE TITLE
Circumvent the need of putting <form> tag at the very top of the page

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#656] opened 2015-03-13 09:45 UTC
Right now `RenderBegin()` for a `QForm` object prints a `<form>` element on page. Everything within the page which is to be controlled by QCubed must reside between the starting and closing tags of this tag. Hence, in most cases, the entire page is contained inside a form element.

By the rules of HTML, one form tag cannot be put inside another form tag. This limits our use of other plugins (especially jQuery UI based libraries) which want a `form` tag to be present for them to function properly. Sometimes, it can also hinder the application of a third party widget on the page.

At the same time, it is noticeable that we do all the postbacks (both Ajax and Server calls) using javascript. Collecting the states of checkable controls (radio buttons and checkboxes) is done using javascript too. So the usage of a huge form is to make sure that all the input elements are submitted back to the QForm automatically.

If we collect the values of all input elements using the list of registered controls (`qc.regCA`), then we can condense the `<form>` tag to a small one by putting all values in one element (like `Qform__FormUpdates`) and sending this to the serverside. This will give the developer a lot more freedom than what one gets now. Using this technique, the framework can be easily made to receive values of even those elements which were not produced by it. It will allow the page to become a lot more versatile. Since controls created by us can be tracked by `qcubed.registerControlArray` and actions be managed using the jQuery command we issue when `RenderEnd()` gets called, I believe compressing the form element to be only at the bottom of page is possible. With 3.0's "send back only the changed controls" approach, it also becomes more feasible and meaningful.

Are there any problems which might occur in such a case?

**Comment by spekary** [comment] 2015-03-15 01:49
Not quite sure what you are getting at. RenderBegin opens the form, and RenderEnd closes the form, and then outputs javascript related to that form. The developer is currently free to hand code other forms outside of that and handle them in PHP. It sounds like you are saying that you would like these hand coded forms and controls be included in the form state? 

The one issue to be careful of is that we currently output the dialogs last, because of a problem with jQuery UI and the overlay generated for dialogs.

>This limits our use of other plugins (especially jQuery UI based libraries) which want a form tag to be present for them to function properly. Sometimes, it can also hinder the application of a third party widget on the page.

Which libraries specifically? Everything I have run into so far I have been able to code as a QControl and get around some kind of limitation. For example, if you take the Bootstrap documentation at face value, they would want you to make separate forms for input groups, but you can easily assign input group classes to div tags and not form tags, and it works just fine.

QForm's RenderAjax section in particular has many things done in a particular order, and if not done in that order, bugs pop up. Again, not sure how it relates to non-QControl javascript controls, but it might.

So, I think giving a more specific description of what widget you are trying to implement that isn't playing well with the current architecture would make it easier to evaluate what you want. If I understand you.

**Comment by vaibhav-kaushal** [comment] 2015-03-17 06:02
I will answer in the order you have said. 

No, I am not asking those things to be into FormState at all. It is already bulky as it is. 

I have solved that problem by creating subclass and using GetEndScript to produce some additional JS which makes sure the overlay is set properly no matter when I render the dialog.

I was trying to use a jQuery uploader (https://blueimp.github.io/jQuery-File-Upload/). The problem is - I was trying to build a plugin around it so that I could do offload my file upload and management worries with ease onto that plugin. But all code failed. Reason - I could not 'Render' that plugin because it would produce a `<form>` element. This element would be inside the form created by RenderBegin. Failure in such cases is inevitable. Also, I have a need to create a form which submits to another site but has to be placed in the middle of the page (while the controls are still rendering). The later one has been worked for now but it is a temporary solution (and an uncomfortable one). There is a third point where I have to introduce live chat which uses another server working on NodeJS. This one wants input elements to be there (entering text for chat). The trouble is: if I try AJAX on that page, things fail because either the input tag for the live chat was not recognized on the server side and crashes the form or if I produce it using QForm then AJAX output will reset the controls and everything stops working.

Also, intuitively - why should the whole page (almost) be a huge form anyway? It is a recipe for trouble. 

So what I propose is produce something like this: 

```
<body>
<!-- Controls being rendered freely like below -->
<input id="c23" type="text" />
<!-- More such controls -->

<!-- Some other controls (e.g. for live chat) -->
<input id="chat_plugin_textentery" type="textbox" />
<input id="chat_plugin_submit_text" type="submit" />

<!-- FormRender (as one step could produce code like below) -->
<form action="some_qform_page.php" method="post">
<input type="hidden" name="Qform__FormControl" id="Qform__FormControl" value="" />
<input type="hidden" name="Qform__FormEvent" id="Qform__FormEvent" value="" />
<input type="hidden" name="Qform__FormParameter" id="Qform__FormParameter" value="" />
<input type="hidden" name="Qform__FormCallType" id="Qform__FormCallType" value="" />
<input type="hidden" name="Qform__FormUpdates" id="Qform__FormUpdates" value="" />
<input type="hidden" name="Qform__FormCheckableControls" id="Qform__FormCheckableControls" value="" />
<!-- New entry like: -->
<input type="hidden" name="Qform__FormElementValues" id="Qform__FormElementValues" value='{"c23":"text entered in the input box", "c24":"checked"}' />
</form>
<!-- then the usual JS-->
<script>
$j("#c6").on("click", function(event, ui) {
qc.pA('Index', 'c6', 'QClickEvent#a1', '', 'PageAjaxWaitIcon'); event.preventDefault(); 
});
</script>
</body>
```

Then in qcubed.js, we could iterate over registeredControls and fill the value of `Qform__FormElementValues` input element (I have given the values for demonstration) and then submit the form. I do not think it would cause too much trouble!

This would be valid because W3C does not mandate input controls to be only inside form tag. Also, it will make sure that we can freely put a handwritten input control in template files (this would be of tremendous value when testing complicated pre-designed pages made by a designer). 

There are many more benefits. There might be some drawbacks too which we might find when implementing (I guess some around QControlProxy might be there). For now, how's the idea?

**Comment by vmakre** [comment] 2015-12-29 11:34
Very interesting discussion regarding qcubed core system functionality. Using third party plugins is sometime problematic especially when we make qcubed plugin class for using third party library with specific javascript functions and some form events without collision with QForm. Maybe here is some idea with using panel or qpanel instead of QForm  . Form element is always generated with render_begin and all elements are post-ed by this form with Qserveraction. But what when we don't need form but we are using only javascript Qajaxaction . Will be a good idea to remove QForm and rename it QPage and  using panel or QPanel with parameter form enabled(disabled) and  if form is enabled then we can make post or get of objects in panel . But when we are not using form then we can make Qajaxaction of objects in panel. All elements in page will have Pagestate instead of Formstate for saving objects values in server. In template we can use panel_render function which can check form enable or disable for render html form element .

**Comment by spekary** [comment] 2015-12-29 18:44
I like the direction of this. It might be tricky, but I think doable.

To sum up, you want to be able to have qcubed controls in various places in a window, mixed in with 3rd party controls that include form tags. You can't do that now because all of the qcubed controls in a window are required to be inside the form tags created by qcubed, and html does not allow a form inside of another form.

@vmakre you are making the point that with ajax these days, why even use a form? I think the only really required place to use a form in the framework is when submitting a file using traditional html file upload. Ajax will not work with the standard file input element. With js file upload widgets, that is less of an issue, but we still want to support all the standard html widgets, so for now, we are going to need to support form submit through QServerActions. It would be difficult as a framework for us to abandon this.

Regarding iterating over all the registered controls: not sure that is needed. I made some changes in 3.0 such that whenever a control changes, it registers the change through formObjChanged in qcubed.js. This was an effort to reduce the amount of data needed to collect and send to the server every time an ajax call was made. It seems to be working and has produced much more responsive ajax, but it requires plugins to be aware that they need to make sure formObjChanged gets called. Most of the time, its automatic through the change and input events, but some widgets don't trigger those, and so need to do this manually.

@vaibhav-kaushal you make the point that html5 allows us to place widgets outside of the form. The problem is that its not supported in IE10 and earlier. I couldn't find anything about it on IE11. Does anyone know?

Here is what I propose. I think its the easiest change and most compatible:

Create a blnUseElementFormTags flag in QForm. When this is turned on, the following happens:
- The form open tag gets sent during RenderEnd, instead of RenderBegin.
- All QControls output a form attribute that has the form id
- If a QServerAction is attempted, we throw an exception stating that QServerActions are not allowed when blnUseElementFormTags is true because its not supported by IE.

The only thing this approach would absolutely prevent is the situation of multiple 3rd party forms mixed in with QCubed form objects, and also using the file upload element. We should leave blnUseElementFormTags as false by default for backward compatibility.

**Comment by kukrik** [comment] 2015-12-29 20:44
@vaibhav-kaushal, I noticed in your question, which was posted on March 17. You asked https://blueimp.github.io/jQuery-File-Upload/. @vakopian was done a few years ago after a 2.x.x version. But it was never completed (https://github.com/vakopian/QJqFileUpload)...

Perhaps it would be wiser to carry him to the end started. And do Qcubed 3.0 apart?

**Comment by spekary** [comment] 2017-07-07 06:20
I am closing this. IE does not support the html5 "form" attribute, and it looks like Microsoft has no future plans to support this.

Glancing through the JQueryFileUpload documentation, I believe this widget can be implemented as QCubed plugin. If you still want this, I can offer some help making it work. See the QCubed v4 examples documentation. At the end, I describe how to make a library. File uploads are tricky, but I believe it can be done. That is one issue.

A separate issue is supporting multiple forms on a page. I believe this also can be done. We would have to make  a kind of form control that would automatically draw after renderEnd. But yes, it could be done if needed. If you still want this, open up a separate issue for this particular need with a specific example.

**Closed by spekary** 2017-07-07 06:20 UTC
